blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ DÃºvidas gerais
    url: https://github.com/SEU_USUARIO/SEU_REPOSITORIO/discussions
    about: Use as discussÃµes para dÃºvidas ou ideias gerais.
